# Generated by Django 2.2.17 on 2021-03-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writecloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createstory',
            options={'verbose_name_plural': 'CreateStories'},
        ),
        migrations.AddField(
            model_name='createstory',
            name='contributors',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
