# Generated by Django 2.2 on 2021-03-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writecloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/default-avatar.png', upload_to='images/'),
        ),
    ]
