# Generated by Django 3.1.7 on 2021-03-28 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writecloud', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='include_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='template',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
