# Generated by Django 3.1.7 on 2021-03-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writecloud', '0003_auto_20210320_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
