# Generated by Django 3.1.7 on 2021-03-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writecloud', '0004_auto_20210320_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
