# Generated by Django 3.1.7 on 2021-03-29 22:44

from django.db import migrations, models
import writecloud.models


class Migration(migrations.Migration):

    dependencies = [
        ('writecloud', '0004_auto_20210328_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(default=None, upload_to='media/images/'),
        ),
    ]
