# Generated by Django 3.1.7 on 2021-03-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writecloud', '0005_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
