# Generated by Django 3.1.7 on 2021-03-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writecloud', '0005_auto_20210320_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
