# Generated by Django 3.1.7 on 2021-03-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writecloud', '0006_auto_20210330_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
