# Generated by Django 3.1.7 on 2021-04-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writecloud', '0007_story_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_author_story_review',
        ),
    ]
