# Generated by Django 3.1.7 on 2021-04-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writecloud', '0008_auto_20210402_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'story'), name='unique_author_story_review'),
        ),
    ]
