# Generated by Django 2.2 on 2021-04-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writecloud', '0009_auto_20210402_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
